### ISSUE TITLE
(android) Status bar color of the Instabug activity is wrong

### ISSUE THREAD

**Issue by SudoPlz** [Instabug/instabug-reactnative#91]
The status bar color is not the same as the app status bar color when the Instabug activity get's launched.

Here's the app:

![instabugstatusbar](https://user-images.githubusercontent.com/3070948/32842306-69a9826e-ca25-11e7-937d-f38f6fc1604d.png)

As you can see the status bar bg color is dark blue.

Here's how Instabug looks like:
![appstatusbar](https://user-images.githubusercontent.com/3070948/32842237-3680b5a6-ca25-11e7-93e1-e692f7a32e19.png)
It's the default grey bg color.

Is there any way to change this?
Thank you

**Comment by ZiadAyman** [comment]
Hey @SudoPlz Thanks for reporting this to us :)

Instabug has two themes the light one and the dark one. Once the SDK is invoked, some changes occur like what you see in your status bar to match the current theme of the SDK. 

We'll definitely consider having something more customizable for future references. Thank you again for pointing out this.

**Comment by Alex100** [comment]
It is possible to change the status bar color: Paste these lines after setting the theme:
`import com.instabug.library.settings.SettingsManager;`

`SettingsManager.getInstance().setStatusBarColor(ResourcesCompat.getColor(getResources(), R.color.focus_red_dark, null));`

However, changing the brightness of the status bar icons is not possible. Instabug must provide a light theme with dark action bar out of the box otherwise any app which is using this kind of theme looks very ugly:
![image](https://user-images.githubusercontent.com/4115023/41363605-9ca34c86-6f34-11e8-9192-8c5df97e1b13.png)
So please provide a third `com.instabug.library.InstabugColorTheme` theme which extends `Light.DarkActionBar` theme under the hood.

**Comment by SudoPlz** [comment]
@Alex100 where do you run this code?

I added
```
SettingsManager.getInstance()
                .setStatusBarColor(ResourcesCompat.getColor(getResources(), R.color.navBarColor, null));
```
 inside the `onCreate` in `MainApplication.java` and I get

```
java.lang.RuntimeException: Unable to create application com.acuityscheduling.app.android.MainApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.instabug.library.settings.a.b(int)' on a null object reference
```

**Comment by SudoPlz** [comment]
Ok I ran this code in createAdditionalReactPackages and it worked.. But yeah, it's in light theme mode.
